In [1]:
import pyscf
from pyscf.tools import cubegen
import matplotlib.pyplot as plt
import numpy as np
import pyscf.lo as lo

def find_t(N=2, r=1.4):
    mol = pyscf.gto.M(
    atom=";". join( f"H 0. 0. {i*r}" for i in range(N)),
    basis='ccpvtz',
    )

    mf = pyscf.scf.RHF(mol)

    mf.kernel()
    mo_occ = mf.mo_coeff[:,0:N]
    a = lo.iao.iao(mol, mo_occ)

    # Orthogonalize IAO
    a = lo.vec_lowdin(a, mf.get_ovlp())

    R = np.einsum("ji,jk,kl->il", a, mf.get_ovlp(), mo_occ)
    print(R.shape)
    ts = np.einsum("ij,j,kj->ik", R, mf.mo_energy[0:N],R)
    print(ts)
    return ts


In [2]:
find_t(N=2)

converged SCF energy = -1.02314024471859
(2, 2)
[[-0.20220518 -0.25195754]
 [-0.25195754 -0.20220518]]


array([[-0.20220518, -0.25195754],
       [-0.25195754, -0.20220518]])

In [3]:
find_t(N=4)

converged SCF energy = -2.04340408163608
(4, 4)
[[-0.19654878 -0.25563646  0.0147416   0.01980874]
 [-0.25563646 -0.19013945 -0.17412852  0.0147416 ]
 [ 0.0147416  -0.17412852 -0.19013945 -0.25563646]
 [ 0.01980874  0.0147416  -0.25563646 -0.19654878]]


array([[-0.19654878, -0.25563646,  0.0147416 ,  0.01980874],
       [-0.25563646, -0.19013945, -0.17412852,  0.0147416 ],
       [ 0.0147416 , -0.17412852, -0.19013945, -0.25563646],
       [ 0.01980874,  0.0147416 , -0.25563646, -0.19654878]])

In [4]:
find_t(N=6)

converged SCF energy = -3.06561644808724
(6, 6)
[[-0.19795825 -0.2537689   0.0168517   0.01707231 -0.00172959 -0.00485281]
 [-0.2537689  -0.19207856 -0.18324797  0.01997682  0.00189323 -0.00172959]
 [ 0.0168517  -0.18324797 -0.17131245 -0.27013395  0.01997682  0.01707231]
 [ 0.01707231  0.01997682 -0.27013395 -0.17131245 -0.18324797  0.0168517 ]
 [-0.00172959  0.00189323  0.01997682 -0.18324797 -0.19207856 -0.2537689 ]
 [-0.00485281 -0.00172959  0.01707231  0.0168517  -0.2537689  -0.19795825]]


array([[-0.19795825, -0.2537689 ,  0.0168517 ,  0.01707231, -0.00172959,
        -0.00485281],
       [-0.2537689 , -0.19207856, -0.18324797,  0.01997682,  0.00189323,
        -0.00172959],
       [ 0.0168517 , -0.18324797, -0.17131245, -0.27013395,  0.01997682,
         0.01707231],
       [ 0.01707231,  0.01997682, -0.27013395, -0.17131245, -0.18324797,
         0.0168517 ],
       [-0.00172959,  0.00189323,  0.01997682, -0.18324797, -0.19207856,
        -0.2537689 ],
       [-0.00485281, -0.00172959,  0.01707231,  0.0168517 , -0.2537689 ,
        -0.19795825]])

In [1]:
t = find_t(N=8)

NameError: name 'find_t' is not defined